name: mywork
on: [ push ]

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: go-example/go.mod
          go-build-target: github.com/YOHAHDS/Assignment/go-example/cmd/octocat
          go-build-args: -o bin/octocat

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: octocat-binary
          path: bin/octocat
