name: mywork
on:
  push:
    branches:
      - 'release/v1.0' 
jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      

      - uses: actions/setup-node@v2
        with:
              node-verson: '16.x'

      - name: Setup go 
        uses: actions/setup-go@v2

        with:
          go-mod-path: go.mod
          go-build-target: all

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: octocat-binary
          path: bin/

# TEST FOR RAILWAY
# test