
name: mywork
on: [ push ]

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Go Dependency Submission
        uses: actions/go-dependency-submission@v1

        with:
          go-mod-path: YOHAHDS/Assignment
          go-build-target: all

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: octocat-binary
          path: bin/

