
name: mywork
on: [ push ]

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2.5.2

      - uses: actions/setup-go@v2.2.1

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: YOHAHDS/Assignment
          go-build-target: YOHAHDS/Assignment/origin

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: octocat-binary
          path: bin/

